language: ruby
sudo: false
cache: bundler
services:
  - redis-server
rvm:
  - 2.1.7
  - 2.0.0
  - 2.2.3
  - jruby
  - jruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-head
